window:
  padding:
    x: 30
    y: 15 #25

  dynamic_padding: false
  opacity: 0.92
  title: Alacritty
  
  class:
    instance: Alacritty
    general: Alacritty

scrolling:
  history: 5000

font: # Cascadia Code
  normal:
    family: CaskaydiaCove Nerd Font
    style: Regular
  bold:
    family: CaskaydiaCove Nerd Font
    style: Bold
  italic:
    family: CaskaydiaCove Nerd Font
    style: Italic
  bold_italic:
    family: CaskaydiaCove Nerd Font
    style: Bold Italic
  size: 15.0

custom_cursor_colors: true
colors:
  primary:
    background: '0x282828'
    foreground: '0xdfbf8e'
  cursor:
    text: '0x1d2021'
    cursor: '0xd5c4a1'
    blinking: Never
  vi_mode_cursor:
    text: CellBackground
    cursor: CellForeground
  search:
    matches:
      foreground: '#282C34'
      background: '#E5C07B'
    focused_match:
      foreground: '#282C34'
      background: '#98C379'
    bar:
      background: '#282C34'
      foreground: '#ABB2BF'
    line_indicator:
      foreground: None
      background: None
    selection:
      text: CellForeground
      background: '#282C34'
 # Normal colors
  normal:
    black:   '0x1d2021'
    red:     '0xfb4934'
    green:   '0xb8bb26'
    yellow:  '0xfabd2f'
    blue:    '0x83a598'
    magenta: '0xd3869b'
    cyan:    '0x8ec07c'
    white:   '0xd5c4a1'

  # Bright colors
  bright:
    black:   '0x665c54'
    red:     '0xfe8019'
    green:   '0x3c3836'
    yellow:  '0x504945'
    blue:    '0xbdae93'
    magenta: '0xebdbb2'
    cyan:    '0xd65d0e'
    white:   '0xfbf1c7'

draw_bold_text_with_bright_colors: false

key_bindings:
  - { key: V,         mods: Control|Shift, action: Paste                       }
  - { key: C,         mods: Control|Shift, action: Copy                        }
  - { key: Insert,    mods: Shift,         action: PasteSelection              }
  - { key: Key0,      mods: Control,       action: ResetFontSize               }
  - { key: Plus,      mods: Control,       action: IncreaseFontSize            }
  - { key: Minus,     mods: Control,       action: DecreaseFontSize            }
  - { key: L,         mods: Control,       action: ClearLogNotice              }
  - { key: L,         mods: Control,       chars: "\x0c"                       }
  - { key: PageUp,    mods: None,          action: ScrollPageUp,   mode: ~Alt  }
  - { key: PageDown,  mods: None,          action: ScrollPageDown, mode: ~Alt  }
  - { key: Home,      mods: Shift,         action: ScrollToTop,    mode: ~Alt  }
  - { key: End,       mods: Shift,         action: ScrollToBottom, mode: ~Alt  }
  - { key: Period,    mods: Control,       chars: "\x1b[46;5u" }
  - { key: Comma,     mods: Control,       chars: "\x1b[44;5u" }
  - { key: Slash,     mods: Control,       chars: "\x1b[47;5u" }
  - { key: Return,    mods: Control,       action: SpawnNewInstance }
  - { key: Space,    mods: Control,       action: ToggleViMode }
  - { key: 5,         mods: Shift,         mode: Vi|~Search,      action: Last                    }
